### ISSUE TITLE
Get a message "YAACC isn't responding"

### ISSUE THREAD

**Issue by rarroyo6** [tobexyz/yaacc-code#131] opened 2024-11-25 03:08 UTC
I'm using YAACC only as a DLNA player to play audio, I have only enabled the "media receiver service".
I'm sending the audio from [Home Assistant](https://www.homeassistant.io) using their [DLNA](https://www.home-assistant.io/integrations/dlna_dmr/) integration.
When I send media to the tablet, the media plays fine, but it immediately displays a "YAACC isn't responding" message, even thou the media continues to play. Clicking on "Wait", makes the message goes away for a few seconds, but it comes back.
I'm running on LineageOS with android ver. 8.1.0, YACC is ver. 4.2.0.

**Comment by tobexyz** [comment] 2024-11-30 09:46
Is there any related information show in the log? Maybe this could help finding the cause

**Comment by rarroyo6** [comment] 2024-12-04 01:07
How do I view the logs so I can report back?

**Comment by tobexyz** [comment] 2024-12-04 21:30
There is an item for showing the log in the menu of the app. The log level is adjustable in the settings

**Comment by tobexyz** [comment] 2024-12-25 21:03
I was able to reproduce the problem. After I removed a bit code and did some cleanups the problem was gone. 
The change will be part of the next upcoming release. So I'll close the ticket for the moment. If it still persist with the new version of the app on your site fell free to give response

**Closed by tobexyz** 2024-12-25 21:03 UTC
