### ISSUE TITLE
[crash on startup]

### ISSUE THREAD

**Issue by vincent456** [tobexyz/yaacc-code#12] opened 2019-01-08 14:42 UTC
The app simply crash on startup. Nothing can really be said except my phone run on Android 8.1.0 (OnePlus A5000, OxygenOS 5.1.7)
I would have built the project to give you the java error message but I have troubles building it on either windows or linux (for example, on linux I have a
`Execution failed for task ':clingbuild:build'.
> A problem occurred starting process 'command 'mvn''
`)

**Comment by tobexyz** [comment] 2019-01-08 16:47
You have to install Maven if you want to build the project.

But you can also attach your device with adb and open the log. If you start the app then, there must be an exception shown in the log

**Comment by vincent456** [comment] 2019-01-08 18:14
Got the project working and I can confirm : it crashes on startup with the default android emulator Nexus 5 API 28 x86 (Android 9.0)

**Comment by tobexyz** [comment] 2019-01-09 20:55
I was able to start the app using an emulator with Android 28. But I've found some problems during service start in the log. So do you have stack trace of the crash?

**Comment by vincent456** [comment] 2019-01-10 16:14
Okay, so the good news is : the app is simply slow, that's why I get "the app is not responding" message but I can tell Android to wait and it seems to work. Now I don't seem to see anything in the categories but I think that should be another issue ? I'll give you a log if you want but when I debug the app everything is fine, the crash only happen on the test of the release version.

**Comment by tobexyz** [comment] 2019-01-10 19:05
Great thx. I think I've to focus on issue #9 and #16 in order to fix the hanging app. 
After that I have to take a look why the released version doesn't work.

**Comment by tobexyz** [comment] 2019-01-13 13:01
I've implemented a first solution in branch ```issue#9```. Items now loaded async. It would be helpful if anyone can additionally confirm that the implementation on the branch fixes the problem that the app hangs.

**Comment by vincent456** [comment] 2019-01-13 14:03
So far with my real phone the "app not responding" keeps popping repeatitively, don't really know why. Plus I had to install the release apk through Android Studio, couldn't do it with the default apk installer of the phone "app not installed". Can anyone _else_ confirm.
P.S. : I have a huge music library on my phone (17Gb)

**Comment by tobexyz** [comment] 2019-01-13 16:32
@vincent456 Interesting, I was able to run the app using branch ```issue#9``` on an Android Pie Emulator. The Emulator is very slow but the app works. Because of the emulator network settings a UPnP server only appears after activating the Yaacc UPnP server for serving test content. You can activate it in the app settings. 
Your installation problem might be caused by a previous installed a version of the app signed by another issuer. This can be the case if you switch between debug and release builds of an apk.

**Comment by tobexyz** [comment] 2019-01-27 19:00
I've just released version 2.2.0 and it will be available on f-droid in a few days. Please check if the bug is fixed then

**Comment by tobexyz** [comment] 2019-03-13 12:47
fixed with 2.2.0

**Closed by tobexyz** 2019-03-13 12:47 UTC
Labels: bug
